services:
  # ollama:
  #   build: .
  #   ports:
  #     - "11434:11434" # apagar em producao
  #   volumes:
  #     - ./ollama:/root/.ollama
  #   devices:
  #     - /dev/kfd
  #     - /dev/dri

# services:
#   proxy:
#     image: nginx:1.27
#     restart: always
#     volumes:
#         - ./conf-proxy:/etc/nginx/conf.d/
#         - ./certs:/etc/nginx/certs/
#     ports:
#         - 80:80
#         - 443:443
#     networks:
#         - proxy

  veia-api:
    image: jefaokpta/veia-api:1.5
    command: ["java", "-Xms700m", "-Xmx700m", "-jar", "/veia-api.jar"]
    networks:
      - proxy
    volumes:
      - ./documents:/documents
    environment:
      - OLLAMA_URL=http://ollama:11434
      - DOCUMENTS_PATH=./documents
      - OPENAI_API_KEY=${OPENAI_API_KEY}

networks:
  proxy:
