services:
  ollama:
    build: .
    ports:
      - "11434:11434" # apagar em producao
    volumes:
      - ./ollama:/root/.ollama
    devices:
      - /dev/kfd
      - /dev/dri

  # veia-api:
  #   image: jefaokpta/veia-api:1.1
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./documents:/documents:ro
  #   environment:
  #     - OLLAMA_URL=http://ollama:11434
  #     - DOCUMENTS_PATH=/documents
