services:
  ollama:
    build: .
    volumes:
      - ./ollama:/root/.ollama
    devices:
      - /dev/kfd
      - /dev/dri

  veia-api:
    image: jefaokpta/veia-api:1.0
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_URL=http://ollama:11434
